name: Deploy to Raspberry Pi via PiTunnel with systemd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy and restart service on Raspberry Pi
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: uk1.pitunnel.net
        port: 58487
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          cd ~/raspi-hello
          git reset --hard HEAD
          git clean -fd
          git pull origin main
          sudo systemctl restart raspi-hello.service
          sleep 3
          echo "Service status:"
          sudo systemctl status raspi-hello.service --no-pager
