name: CI and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run tests
        run: python -m unittest test_app.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd ~/raspi-hello
            git pull origin main
            pkill -f app.py || true
            nohup python3 app.py > app.log 2>&1 &
            ~/raspi-hello/deploy.sh
