name: Deploy to Raspberry Pi over ZeroTier SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install ZeroTier One
      run: |
        curl -s https://install.zerotier.com | sudo bash

    - name: Join ZeroTier network
      run: |
        sudo zerotier-cli join ${{ secrets.ZEROTIER_NETWORK_ID }}

    - name: Wait for ZeroTier to connect
      run: |
        for i in {1..10}; do
          status=$(zerotier-cli info)
          if [[ "$status" == *"OK"* ]]; then
            echo "Joined ZeroTier network"
            break
          fi
          echo "Waiting for ZeroTier authorization..."
          sleep 10
        done

    - name: Run deployment script on Raspberry Pi
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PI_ZEROTIER_IP }}       # Pi ZeroTier IP stored as a secret
        username: ${{ secrets.PI_USER }}                             # or your Pi username
        key: ${{ secrets.SSH_PRIVATE_KEY }}      # SSH private key stored as secret
        script: |
          cd ~/raspi-hello
          git pull origin main
          # add other commands you want to run on the Pi
